
DROP SCHEMA IF EXISTS SAP_UABC;

CREATE SCHEMA IF NOT EXISTS SAP_UABC;

USE SAP_UABC;

CREATE TABLE IF NOT EXISTS USUARIO(
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY);

CREATE TABLE IF NOT EXISTS REVISTA(
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY);

CREATE TABLE IF NOT EXISTS PROGRAMA(
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY);

CREATE TABLE IF NOT EXISTS CUERPO_ACADEMICO(
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY);

CREATE TABLE IF NOT EXISTS PRODUCTO(
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
id_revista INT,
id_usuario INT NOT NULL,
archivo TEXT NOT NULL,
nombre_autor VARCHAR(255),
apellido_paterno_autor VARCHAR(255),
apellido_materno_autor VARCHAR(255),
grado_estudio_autor VARCHAR(255),
nombre_articulo VARCHAR(250) NOT NULL,
issn_articulo VARCHAR(250),	
indizado TINYINT NOT NULL,
arbitraje TINYINT NOT NULL,
fecha_publicacion VARCHAR(10)
);

ALTER TABLE PRODUCTO ADD CONSTRAINT fk_id_revista FOREIGN KEY (id_revista) REFERENCES REVISTA(id) ON DELETE NO ACTION ON UPDATE NO ACTION,
ADD CONSTRAINT fk_id_usuario FOREIGN KEY (id_usuario) REFERENCES USUARIO(id) ON DELETE NO ACTION ON UPDATE NO ACTION;
