
DROP SCHEMA IF EXISTS SAP_UABC;

CREATE SCHEMA IF NOT EXISTS SAP_UABC;

USE SAP_UABC;


CREATE TABLE IF NOT EXISTS USUARIO(
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY);

CREATE TABLE IF NOT EXISTS REVISTA(
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY);

CREATE TABLE IF NOT EXISTS PROGRAMA(
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY);

CREATE TABLE IF NOT EXISTS CUERPO_ACADEMICO(
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY);

CREATE TABLE IF NOT EXISTS PRODUCTO(
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
id_revista INT,
id_usuario INT NOT NULL,
id_autor INT NOT NULL,
archivo TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS ARTICULO(
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
id_producto INT NOT NULL,
nombre_articulo VARCHAR(250) NOT NULL,
issn VARCHAR(250),	
indizado TINYINT NOT NULL,
arbitraje TINYINT NOT NULL);

CREATE TABLE IF NOT EXISTS AUTOR(
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
nombre VARCHAR(255),
apellido_paterno VARCHAR(255),
apellido_materno VARCHAR(255),
grado SET("academico","estudiante maestria","estudiante doctorado"));

ALTER TABLE PRODUCTO ADD CONSTRAINT fk_id_revista FOREIGN KEY (id_revista) REFERENCES REVISTA(id) ON DELETE NO ACTION ON UPDATE NO ACTION,
ADD CONSTRAINT fk_id_usuario FOREIGN KEY (id_usuario) REFERENCES USUARIO(id) ON DELETE NO ACTION ON UPDATE NO ACTION,
ADD CONSTRAINT fk_id_autor FOREIGN KEY (id_autor) REFERENCES AUTOR(id) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE ARTICULO ADD CONSTRAINT fk_id_producto FOREIGN KEY(id_producto) REFERENCES PRODUCTO(id) ON DELETE NO ACTION ON UPDATE NO ACTION;